# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin:
          - exec-capture-output
        target:
          - x86_64-unknown-linux-musl
          # Add other targets here
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --manifest-path ./${{ matrix.bin }}/Cargo.toml
          # working-directory: ${{ matrix.bin }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.bin }}
          path: ${{ matrix.bin }}/target/x86_64-unknown-linux-musl/release/${{ matrix.bin }}